db:
  host: localhost
  port: 5432
  database: telemetry
  user: postgres
  password: "rabin@#123"

mail:
  server: smtp.elasticemail.com
  email: telemetry@sistadm.us
  password: "B72E06C96240D71841593D60F253DA452EC8"
  port: 2525